name: Playwright Multi Environment Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:

  test:

    strategy:
      matrix:
        environment: [qa, stage]

    runs-on: ubuntu-latest

    environment: ${{ matrix.environment }}

    env:
      ENV: ${{ matrix.environment }}

      BASE_URL: ${{ vars.BASE_URL }}

      APP_USERNAME: ${{ secrets.APP_USERNAME }}
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      API_TOKEN: ${{ secrets.API_TOKEN }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Show selected environment
        run: |
          echo "Running on environment: $ENV"
          echo "Base URL: $BASE_URL"

      - name: Run Smoke Tests on PR
        if: github.event_name == 'pull_request'
        run: npx playwright test --grep "@smoke"
      
      - name: Run Smoke Tests on Schedule
        if: github.event_name == 'schedule'
        run: npx playwright test --grep "@regression"    
      - name: Run Smoke Tests on Run Tests Manually
        if: github.event_name == 'workflow_dispatch'
        run: npx playwright test 

      - name: Upload Playwright Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v5
        with:
          name: playwright-report-${{ matrix.environment }}
          path: reports/html-report/
          retention-days: 30
      - name: Setup Java for Allure
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Generate Allure Report
        if: ${{ !cancelled() }}
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v5
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30
